[package]
name = 'Mira'
version = '0.0.0'

[dependencies]
AptosFramework = { local = "../aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
Std = "0x1"
mira = "0x59B0135F93FC9C89613523D47A92E652A57A42193F463AE9D4BD17188ED7CC93"
